package pojos;
// Generated Nov 12, 2017 8:05:52 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer msgId;
     private User user;
     private Chatroom chatroom;
     private String msg;
     private Date msgTime;

    public Message() {
    }

	
    public Message(User user, Chatroom chatroom) {
        this.user = user;
        this.chatroom = chatroom;
    }
    public Message(User user, Chatroom chatroom, String msg, Date msgTime) {
       this.user = user;
       this.chatroom = chatroom;
       this.msg = msg;
       this.msgTime = msgTime;
    }
   
    public Integer getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Chatroom getChatroom() {
        return this.chatroom;
    }
    
    public void setChatroom(Chatroom chatroom) {
        this.chatroom = chatroom;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public Date getMsgTime() {
        return this.msgTime;
    }
    
    public void setMsgTime(Date msgTime) {
        this.msgTime = msgTime;
    }




}


