package pojos;
// Generated Nov 12, 2017 8:05:52 AM by Hibernate Tools 3.6.0



/**
 * Privatechatroom generated by hbm2java
 */
public class Privatechatroom  implements java.io.Serializable {


     private Integer pcrId;
     private Chatroom chatroom;
     private int user2Id;
     private int user1Id;

    public Privatechatroom() {
    }

    public Privatechatroom(Chatroom chatroom, int user2Id, int user1Id) {
       this.chatroom = chatroom;
       this.user2Id = user2Id;
       this.user1Id = user1Id;
    }
   
    public Integer getPcrId() {
        return this.pcrId;
    }
    
    public void setPcrId(Integer pcrId) {
        this.pcrId = pcrId;
    }
    public Chatroom getChatroom() {
        return this.chatroom;
    }
    
    public void setChatroom(Chatroom chatroom) {
        this.chatroom = chatroom;
    }
    public int getUser2Id() {
        return this.user2Id;
    }
    
    public void setUser2Id(int user2Id) {
        this.user2Id = user2Id;
    }
    public int getUser1Id() {
        return this.user1Id;
    }
    
    public void setUser1Id(int user1Id) {
        this.user1Id = user1Id;
    }




}


